# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Simulator__new <- function(name_, verbose_) {
    .Call('simmer_Simulator__new', PACKAGE = 'simmer', name_, verbose_)
}

reset_ <- function(sim_) {
    invisible(.Call('simmer_reset_', PACKAGE = 'simmer', sim_))
}

step_ <- function(sim_) {
    invisible(.Call('simmer_step_', PACKAGE = 'simmer', sim_))
}

run_ <- function(sim_, until_) {
    invisible(.Call('simmer_run_', PACKAGE = 'simmer', sim_, until_))
}

resource_ <- function(sim_, name_, capacity_, queue_size_, mon_) {
    invisible(.Call('simmer_resource_', PACKAGE = 'simmer', sim_, name_, capacity_, queue_size_, mon_))
}

process_ <- function(sim_, func_) {
    invisible(.Call('simmer_process_', PACKAGE = 'simmer', sim_, func_))
}

timeout_ <- function(sim_, delay_) {
    invisible(.Call('simmer_timeout_', PACKAGE = 'simmer', sim_, delay_))
}

request_ <- function(sim_, name_, amount_) {
    invisible(.Call('simmer_request_', PACKAGE = 'simmer', sim_, name_, amount_))
}

get_mon_arrivals_ <- function(sim_) {
    .Call('simmer_get_mon_arrivals_', PACKAGE = 'simmer', sim_)
}

get_mon_resource_ <- function(sim_, name_) {
    .Call('simmer_get_mon_resource_', PACKAGE = 'simmer', sim_, name_)
}

get_res_capacity_ <- function(sim_, name_) {
    .Call('simmer_get_res_capacity_', PACKAGE = 'simmer', sim_, name_)
}

get_res_queue_size_ <- function(sim_, name_) {
    .Call('simmer_get_res_queue_size_', PACKAGE = 'simmer', sim_, name_)
}

