# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Simulator__new <- function(name, verbose) {
    .Call('simmer_Simulator__new', PACKAGE = 'simmer', name, verbose)
}

reset_ <- function(sim_) {
    invisible(.Call('simmer_reset_', PACKAGE = 'simmer', sim_))
}

now_ <- function(sim_) {
    .Call('simmer_now_', PACKAGE = 'simmer', sim_)
}

peek_ <- function(sim_, steps) {
    .Call('simmer_peek_', PACKAGE = 'simmer', sim_, steps)
}

step_ <- function(sim_) {
    invisible(.Call('simmer_step_', PACKAGE = 'simmer', sim_))
}

run_ <- function(sim_, until) {
    invisible(.Call('simmer_run_', PACKAGE = 'simmer', sim_, until))
}

add_generator_ <- function(sim_, name_prefix, first_activity_, dist, mon, priority, preemptible, restart) {
    .Call('simmer_add_generator_', PACKAGE = 'simmer', sim_, name_prefix, first_activity_, dist, mon, priority, preemptible, restart)
}

add_resource_ <- function(sim_, name, capacity, queue_size, mon, preemptive, preempt_order, keep_queue) {
    .Call('simmer_add_resource_', PACKAGE = 'simmer', sim_, name, capacity, queue_size, mon, preemptive, preempt_order, keep_queue)
}

add_resource_manager_ <- function(sim_, name, param, intervals, values, period) {
    .Call('simmer_add_resource_manager_', PACKAGE = 'simmer', sim_, name, param, intervals, values, period)
}

get_mon_arrivals_ <- function(sim_) {
    .Call('simmer_get_mon_arrivals_', PACKAGE = 'simmer', sim_)
}

get_mon_arrivals_per_resource_ <- function(sim_) {
    .Call('simmer_get_mon_arrivals_per_resource_', PACKAGE = 'simmer', sim_)
}

get_mon_attributes_ <- function(sim_) {
    .Call('simmer_get_mon_attributes_', PACKAGE = 'simmer', sim_)
}

get_mon_resource_ <- function(sim_) {
    .Call('simmer_get_mon_resource_', PACKAGE = 'simmer', sim_)
}

get_mon_resource_counts_ <- function(sim_) {
    .Call('simmer_get_mon_resource_counts_', PACKAGE = 'simmer', sim_)
}

get_mon_resource_limits_ <- function(sim_) {
    .Call('simmer_get_mon_resource_limits_', PACKAGE = 'simmer', sim_)
}

get_n_generated_ <- function(sim_, name) {
    .Call('simmer_get_n_generated_', PACKAGE = 'simmer', sim_, name)
}

set_capacity_ <- function(sim_, name, value) {
    invisible(.Call('simmer_set_capacity_', PACKAGE = 'simmer', sim_, name, value))
}

get_capacity_ <- function(sim_, name) {
    .Call('simmer_get_capacity_', PACKAGE = 'simmer', sim_, name)
}

set_queue_size_ <- function(sim_, name, value) {
    invisible(.Call('simmer_set_queue_size_', PACKAGE = 'simmer', sim_, name, value))
}

get_queue_size_ <- function(sim_, name) {
    .Call('simmer_get_queue_size_', PACKAGE = 'simmer', sim_, name)
}

get_server_count_ <- function(sim_, name) {
    .Call('simmer_get_server_count_', PACKAGE = 'simmer', sim_, name)
}

get_queue_count_ <- function(sim_, name) {
    .Call('simmer_get_queue_count_', PACKAGE = 'simmer', sim_, name)
}

Seize__new <- function(verbose, resource, amount, cont, trj, mask) {
    .Call('simmer_Seize__new', PACKAGE = 'simmer', verbose, resource, amount, cont, trj, mask)
}

Seize__new_func <- function(verbose, resource, amount, provide_attrs, cont, trj, mask) {
    .Call('simmer_Seize__new_func', PACKAGE = 'simmer', verbose, resource, amount, provide_attrs, cont, trj, mask)
}

SeizeSelected__new <- function(verbose, id, amount, cont, trj, mask) {
    .Call('simmer_SeizeSelected__new', PACKAGE = 'simmer', verbose, id, amount, cont, trj, mask)
}

SeizeSelected__new_func <- function(verbose, id, amount, provide_attrs, cont, trj, mask) {
    .Call('simmer_SeizeSelected__new_func', PACKAGE = 'simmer', verbose, id, amount, provide_attrs, cont, trj, mask)
}

Release__new <- function(verbose, resource, amount) {
    .Call('simmer_Release__new', PACKAGE = 'simmer', verbose, resource, amount)
}

Release__new_func <- function(verbose, resource, amount, provide_attrs) {
    .Call('simmer_Release__new_func', PACKAGE = 'simmer', verbose, resource, amount, provide_attrs)
}

ReleaseSelected__new <- function(verbose, id, amount) {
    .Call('simmer_ReleaseSelected__new', PACKAGE = 'simmer', verbose, id, amount)
}

ReleaseSelected__new_func <- function(verbose, id, amount, provide_attrs) {
    .Call('simmer_ReleaseSelected__new_func', PACKAGE = 'simmer', verbose, id, amount, provide_attrs)
}

Select__new <- function(verbose, resources, policy, id) {
    .Call('simmer_Select__new', PACKAGE = 'simmer', verbose, resources, policy, id)
}

Select__new_func <- function(verbose, resources, provide_attrs, id) {
    .Call('simmer_Select__new_func', PACKAGE = 'simmer', verbose, resources, provide_attrs, id)
}

SetAttribute__new <- function(verbose, key, value) {
    .Call('simmer_SetAttribute__new', PACKAGE = 'simmer', verbose, key, value)
}

SetAttribute__new_func <- function(verbose, key, value, provide_attrs) {
    .Call('simmer_SetAttribute__new_func', PACKAGE = 'simmer', verbose, key, value, provide_attrs)
}

SetPrior__new <- function(verbose, values) {
    .Call('simmer_SetPrior__new', PACKAGE = 'simmer', verbose, values)
}

SetPrior__new_func <- function(verbose, values, provide_attrs) {
    .Call('simmer_SetPrior__new_func', PACKAGE = 'simmer', verbose, values, provide_attrs)
}

Timeout__new <- function(verbose, delay) {
    .Call('simmer_Timeout__new', PACKAGE = 'simmer', verbose, delay)
}

Timeout__new_func <- function(verbose, task, provide_attrs) {
    .Call('simmer_Timeout__new_func', PACKAGE = 'simmer', verbose, task, provide_attrs)
}

Branch__new <- function(verbose, option, provide_attrs, cont, trj) {
    .Call('simmer_Branch__new', PACKAGE = 'simmer', verbose, option, provide_attrs, cont, trj)
}

Rollback__new <- function(verbose, amount, times) {
    .Call('simmer_Rollback__new', PACKAGE = 'simmer', verbose, amount, times)
}

Rollback__new_func <- function(verbose, amount, check, provide_attrs) {
    .Call('simmer_Rollback__new_func', PACKAGE = 'simmer', verbose, amount, check, provide_attrs)
}

Leave__new <- function(verbose, prob) {
    .Call('simmer_Leave__new', PACKAGE = 'simmer', verbose, prob)
}

Leave__new_func <- function(verbose, prob, provide_attrs) {
    .Call('simmer_Leave__new_func', PACKAGE = 'simmer', verbose, prob, provide_attrs)
}

RenegeIn__new <- function(verbose, t, trj) {
    .Call('simmer_RenegeIn__new', PACKAGE = 'simmer', verbose, t, trj)
}

RenegeIn__new_func <- function(verbose, t, provide_attrs, trj) {
    .Call('simmer_RenegeIn__new_func', PACKAGE = 'simmer', verbose, t, provide_attrs, trj)
}

RenegeAbort__new <- function(verbose) {
    .Call('simmer_RenegeAbort__new', PACKAGE = 'simmer', verbose)
}

Clone__new <- function(verbose, n, trj) {
    .Call('simmer_Clone__new', PACKAGE = 'simmer', verbose, n, trj)
}

Clone__new_func <- function(verbose, n, provide_attrs, trj) {
    .Call('simmer_Clone__new_func', PACKAGE = 'simmer', verbose, n, provide_attrs, trj)
}

Synchronize__new <- function(verbose, wait, terminate) {
    .Call('simmer_Synchronize__new', PACKAGE = 'simmer', verbose, wait, terminate)
}

Batch__new <- function(verbose, n, timeout, permanent, name) {
    .Call('simmer_Batch__new', PACKAGE = 'simmer', verbose, n, timeout, permanent, name)
}

Batch__new_func <- function(verbose, n, timeout, permanent, name, rule, provide_attrs) {
    .Call('simmer_Batch__new_func', PACKAGE = 'simmer', verbose, n, timeout, permanent, name, rule, provide_attrs)
}

Separate__new <- function(verbose) {
    .Call('simmer_Separate__new', PACKAGE = 'simmer', verbose)
}

activity_get_n_ <- function(activity_) {
    .Call('simmer_activity_get_n_', PACKAGE = 'simmer', activity_)
}

activity_print_ <- function(activity_, indent) {
    invisible(.Call('simmer_activity_print_', PACKAGE = 'simmer', activity_, indent))
}

activity_get_next_ <- function(activity_) {
    .Call('simmer_activity_get_next_', PACKAGE = 'simmer', activity_)
}

activity_get_prev_ <- function(activity_) {
    .Call('simmer_activity_get_prev_', PACKAGE = 'simmer', activity_)
}

activity_chain_ <- function(first_, second_) {
    invisible(.Call('simmer_activity_chain_', PACKAGE = 'simmer', first_, second_))
}

activity_clone_ <- function(activity_) {
    .Call('simmer_activity_clone_', PACKAGE = 'simmer', activity_)
}

