# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Simulator__new <- function(name_, verbose_) {
    .Call('simmer_Simulator__new', PACKAGE = 'simmer', name_, verbose_)
}

reset_ <- function(sim_) {
    invisible(.Call('simmer_reset_', PACKAGE = 'simmer', sim_))
}

schedule_ <- function(delay_, arrival_) {
    invisible(.Call('simmer_schedule_', PACKAGE = 'simmer', delay_, arrival_))
}

run_ <- function(sim_, until_) {
    invisible(.Call('simmer_run_', PACKAGE = 'simmer', sim_, until_))
}

add_generator_ <- function(sim_, name_prefix_, first_event_, dist_) {
    invisible(.Call('simmer_add_generator_', PACKAGE = 'simmer', sim_, name_prefix_, first_event_, dist_))
}

add_resource_ <- function(sim_, name_, capacity_, queue_size_, mon_) {
    invisible(.Call('simmer_add_resource_', PACKAGE = 'simmer', sim_, name_, capacity_, queue_size_, mon_))
}

get_mon_arrivals_ <- function(sim_) {
    .Call('simmer_get_mon_arrivals_', PACKAGE = 'simmer', sim_)
}

get_mon_resource_ <- function(sim_, name_) {
    .Call('simmer_get_mon_resource_', PACKAGE = 'simmer', sim_, name_)
}

get_res_capacity_ <- function(sim_, name_) {
    .Call('simmer_get_res_capacity_', PACKAGE = 'simmer', sim_, name_)
}

get_res_queue_size_ <- function(sim_, name_) {
    .Call('simmer_get_res_queue_size_', PACKAGE = 'simmer', sim_, name_)
}

